
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mysql-operator
rules:
- apiGroups:
  - atlas.aibee.cn
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atlas.aibee.cn
  resources:
  - mysqls/finalizers
  verbs:
  - update
- apiGroups:
  - atlas.aibee.cn
  resources:
  - mysqls/status
  verbs:
  - get
  - patch
  - update
