apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-single-123
  namespace: infra
data:
  mysqld.cnf: |-
    [mysqld]
    server-id=001
    datadir=/var/lib/mysql
    pid-file=/var/lib/mysql/mysqld.pid
    socket=/var/lib/mysql/mysqld.sock
    max-connections=800
    sync-binlog=10
    binlog-format=ROW
    binlog_checksum=NONE
    log-bin=binlog
    expire-logs-days=3
    innodb-buffer-pool-size=34359738368
    innodb-buffer-pool-instances=16
    thread_cache_size=32
    default-password-lifetime=0
    default-storage-engine=innodb
    default-time-zone=SYSTEM
    default-tmp-storage-engine=innodb
    log-timestamps=SYSTEM
    disabled-storage-engines='BLACKHOLE,FEDERATED,ARCHIVE'
    master-info-repository=TABLE
    relay-log-info-repository=TABLE
    transaction-isolation=READ-COMMITTED
    transaction-write-set-extraction=XXHASH64
    innodb-open-files=2000
    innodb-buffer-pool-size=4294967296
    innodb-flush-log-at-trx-commit=2
    innodb-autoinc-lock-mode=2
    innodb-buffer-pool-instances=4
    innodb-log-buffer-size=33554432
    innodb-flush-method=O_DIRECT_NO_FSYNC
    innodb-monitor-enable='%'
    innodb-open-files=128
    innodb-print-all-deadlocks=ON
    innodb-undo-log-truncate=ON
    innodb-undo-logs=2
    innodb-undo-tablespaces=2
    internal-tmp-disk-storage-engine=innodb
    performance-schema-consumer-events-transactions-current=ON
    performance-schema-consumer-events-transactions-history=ON
    sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_520_ci
    binlog-cache-size=1048576
    skip-name-resolve=ON
    max-allowed-packet=13M
    explicit-defaults-for-timestamp=1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-init-sql-123
  namespace: infra
data:
  init.sql: |-
    create database db1;
    create database db2;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-init-sql-test
  namespace: infra
data:
  init.sql: |-
    create database db1;
    create database db2;
---
apiVersion: atlas.aibee.cn/v1beta1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-sample
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-operator
  name: mysql-sample
spec:
  global:
    xtrabackup:
      image: harbor.aibee.cn/platform/xtrabackup:2.4.26-beta.2
  group:
  - name: "test123"
    namespace: infra
    single:
      mysqld:
        image: harbor.aibee.cn/platform/mysql:5.7.37
        rootpassword: root_password
        mycnf_cm: cm-mysql-single-123
        init_sql_cm: cm-mysql-init-sql-123
        request:
          cpu: 1000m
          memory: 2Gi
        limit:
          cpu: 4000m
          memory: 8Gi
      datadir:
        host:
          nodeSelector:
            key: "mysql"
            value: "true"
          #nodename: bj-cpu065
          dir: /mnt/124
  - name: "test456"
    namespace: infra
    service_name: "svc-kk"
    single:
      mysqld:
        image: harbor.aibee.cn/platform/mysql:5.7.37
        rootpassword: root_password
      datadir:
        host:
          nodeSelector:
            key: "mysql"
            value: "true"
          #nodename: bj-cpu067
          dir: /mnt/12444
