apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-single-123
  namespace: infra
data:
  mysqld.cnf: |-
    [mysqld]
    datadir=/var/lib/mysql
    pid-file=/var/lib/mysql/mysqld.pid
    socket=/var/lib/mysql/mysqld.sock
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-init-sql-123
  namespace: infra
data:
  init.sql: |-
    create database db1;
    create database db2;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-mysql-init-sql-test
  namespace: infra
data:
  init.sql: |-
    create database db1;
    create database db2;
---
apiVersion: atlas.aibee.cn/v1beta1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-sample
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mysql-operator
  name: mysql-sample
spec:
  global:
    xtrabackup:
      image: harbor.aibee.cn/platform/xtrabackup:2.4.26-beta.2
  group:
  - name: "test123"
    namespace: infra
    single:
      mysqld:
        image: harbor.aibee.cn/platform/mysql:5.7.37
        rootpassword: root_password
        mycnf_cm: cm-mysql-single-123
        init_sql_cm: cm-mysql-init-sql-123
        request:
          cpu: 1000m
          memory: 2Gi
        limit:
          cpu: 4000m
          memory: 8Gi
      datadir:
        host:
          nodename: bj-cpu065
          dir: /mnt/124
  - name: "test456"
    namespace: infra
    service_name: "svc-kk"
    single:
      mysqld:
        image: harbor.aibee.cn/platform/mysql:5.7.37
        rootpassword: root_password
      datadir:
        host:
          nodename: bj-cpu067
          dir: /mnt/124
